# Nome do pipeline
name: 'Cypress Test Pipeline'

# Dispara o pipeline em eventos de push e pull requests
trigger:
  branches:
    include:
      - main
      - develop

# Pool de agentes (Windows)
pool:
  vmImage: 'windows-latest'

steps:
  # Etapa 1: Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Instalação do Node.js'

  # Etapa 2: Instalar dependências
  - script: |
      npm install
    displayName: 'Instalação das dependências'

  # Etapa 3: Verificar instalação do preprocessor
  - script: |
      npm install @badeball/cypress-cucumber-preprocessor
    displayName: 'Instalação do cypress-cucumber-preprocessor'

  # Etapa 4: Configurar o Cypress
  - script: |
      npx cypress install
      npx cypress verify
    displayName: 'Configuração do Cypress'

  # Etapa 5: Executar os testes do Cypress
  - script: |
      npx cypress run
    displayName: 'Executando os testes do Cypress'

  # Etapa 6: Publicar os resultados dos testes
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results/*.xml'
    displayName: 'Publicar resultados dos testes'
