# Nome do pipeline
name: 'Pipeline Cypress com Cucumber'

# Definir quando o pipeline será executado (em push ou pull requests)
trigger:
  branches:
    include:
      - main
      - develop

# Configuração do ambiente (Windows mais recente)
pool:
  vmImage: 'windows-latest'

# Etapas do pipeline
steps:
  # Etapa 1: Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Instalar Node.js'

  # Etapa 2: Limpar Cache do npm (opcional)
  - script: npm cache clean --force
    displayName: 'Limpar Cache do npm'

  # Etapa 3: Instalar Dependências (inclui cypress-cucumber-preprocessor)
  - script: |
      npm install
      npm install @badeball/cypress-cucumber-preprocessor
    displayName: 'Instalar Dependências'

  # Etapa 4: Verificar Instalação do Preprocessor (para garantir que foi instalado corretamente)
  - script: |
      npm list @badeball/cypress-cucumber-preprocessor
    displayName: 'Verificar Instalação do Preprocessor'

  # Etapa 5: Configurar o Cypress e o Preprocessor
  - script: |
      npx cypress install
      npx cypress verify
    displayName: 'Configuração do Cypress'

  # Etapa 6: Executar Testes com Cypress e Cucumber
  - script: |
      npx cypress run
    displayName: 'Executando os Testes do Cypress'

  # Etapa 7: Publicar Resultados dos Testes
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results/*.xml'
    displayName: 'Publicar Resultados dos Testes'

  # Etapa 8: Limpar Cache do Cypress (opcional, caso ocorra erro de cache)
  - script: npx cypress cache clear
    displayName: 'Limpar Cache do Cypress'

