# Nome do pipeline
name: 'Cypress Test Pipeline'

# Dispara o pipeline em eventos de push e pull requests
trigger:
  branches:
    include:
      - main
      - develop

# Definição de variáveis
variables:
  CYPRESS_BASE_URL: 'https://seu-site-ou-api.com'

# Jobs e pool de agentes
pool:
  vmImage: 'ubuntu-latest'

# Etapas do pipeline
steps:
  # Etapa 1: Instalação do Node.js
  - task: UseNode@2
    inputs:
      version: '16.x'  # Especifique a versão necessária do Node.js

  # Etapa 2: Baixar dependências do projeto
  - script: |
      npm install
    displayName: 'Instalação das dependências'

  # Etapa 3: Execução dos testes Cypress
  - script: |
      npx cypress run
    displayName: 'Executando os testes do Cypress'

  # Etapa 4: Publicar resultados dos testes
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results/*.xml'  # Caso utilize um plugin para Cypress gerar XML
      testRunTitle: 'Resultados dos Testes Cypress'
