# Nome do pipeline
name: 'Cypress Pipeline com Atualização de Dependências'

# Dispara o pipeline em eventos de push e pull requests
trigger:
  branches:
    include:
      - main
      - develop

# Pool de agentes (Windows mais recente)
pool:
  vmImage: 'windows-latest'

# Etapas do pipeline
steps:
  # Etapa 1: Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Instalar Node.js'

  # Etapa 2: Limpar Cache do npm (opcional)
  - script: npm cache clean --force
    displayName: 'Limpar Cache do npm'

  # Etapa 3: Atualizar Dependências Usando Resolutions
  - script: |
      npm install
      npm install -g npm-check-updates
      ncu -u  # Atualiza dependências de acordo com resoluções no package.json
      npm install
    displayName: 'Atualizar Dependências com Resolutions'

  # Etapa 4: Instalar Dependências do Cypress e do Preprocessor
  - script: |
      npm install @badeball/cypress-cucumber-preprocessor
    displayName: 'Instalar Dependências do Cypress e Preprocessor'

  # Etapa 5: Verificar Instalação do Preprocessor (para garantir que foi instalado corretamente)
  - script: |
      npm list @badeball/cypress-cucumber-preprocessor
    displayName: 'Verificar Instalação do Preprocessor'

  # Etapa 6: Configurar e Verificar o Cypress
  - script: |
      npx cypress install
      npx cypress verify
    displayName: 'Configurar o Cypress'

  # Etapa 7: Executar Testes do Cypress com Cucumber
  - script: |
      npx cypress run
    displayName: 'Executando Testes do Cypress'

  # Etapa 8: Publicar Resultados dos Testes
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/results/*.xml'
    displayName: 'Publicar Resultados dos Testes'

  # Etapa 9: Limpar Cache do Cypress (opcional, caso haja erros)
  - script: npx cypress cache clear
    displayName: 'Limpar Cache do Cypress'
